### ISSUE TITLE
Will not work in Production

### ISSUE THREAD

**Issue by mjones2620** [ferrywlto/vdn#13]
Hi,

I've got this working when deployed to localhost/, but when I put this in production (www.somesite.com/myapp/) node services throws a 404 because it will not find matched routes. I tried modifying the base url in vue-router to be /myapp/ but this did not work either. 

Any thoughts?

Thanks,
Matt

**Comment by ferrywlto** [comment]
Sorry I didn't tried on public domain. However I guess when you deployed to public domain it will be HTTPS so you may need to update your vue.config.js. 
Hope this helps. 
https://stackoverflow.com/questions/50877800/how-can-i-fix-these-sockjs-ssl-errors

**Comment by ferrywlto** [comment]
Closing this as inactive.
