### ISSUE TITLE
webpack err

### ISSUE THREAD

**Issue by Jacknq** [ferrywlto/vdn#2]
Hi, 
when i tried your  template with commands you specified, i get error when running webpack
and dotnet run.  
Any other example how to run this?

**Comment by ferrywlto** [comment]
May you specify your environment and version?

**Comment by Jacknq** [comment]
npm 5.5.1, dotnet 2.0

**Comment by ferrywlto** [comment]
@Jack85  I am running the same version as you. Can you share the error or screenshots so I can try to reproduce the error?

**Comment by Jacknq** [comment]
following readme (without instaling webpack globally):
dotnet restore
npm install
webpack
dotnet run

ouputs:

![image](https://user-images.githubusercontent.com/16955647/37333891-b8a14cc6-26aa-11e8-80d5-e443e51063ff.png)

![image](https://user-images.githubusercontent.com/16955647/37334031-192a2612-26ab-11e8-90ff-d7adb35cb1b8.png)

maybe you can try clean download from github and run the commands.

**Comment by ferrywlto** [comment]
seems you didn't install webpack, if you do not want to install webpack globally, you can install it locally via:
npm install --save-dev webpack

**Comment by Jacknq** [comment]
same result, shoudlnt you have command specified in project json?

**Comment by ferrywlto** [comment]
sorry for the late reply, in fact the `webpack` command is not needed in order to run the code unless you want to pack the JavaScript code manually. `aspnet-webpack` package and the .net core JavaScriptService will pack the JavaScript code automatically during runtime. Since webpack 4 split the command line tool to package `webpack-cli`, you may need to install that package too if you want to pack the JavaScript code by your own. I will update the Readme on next release, thanks.

**Comment by Jacknq** [comment]
still the same, its missing that main-server.js on build

**Comment by ferrywlto** [comment]
Hey @Jack85 , sorry I forget to merge the PR. Please try again.

**Comment by Jacknq** [comment]
thanks, still the same \wwwroot\dist\main-server.js doesnt get created by me.

**Comment by ferrywlto** [comment]
@Jack85 When the app run the first time, it may takes a few seconds to built the the `./ClientApp/server.js` into `./wwwroot/dist/main-server.js`. The same apply to `./ClientApp/client.js` too. Once it did, you should see lines like'
```
info: Microsoft.AspNetCore.NodeServices[0]
        webpack built c91dc3e2f186f013c53c in 3212ms
```
in console.

I did delete the repo from my computer and did a clean clone from the master branch and start with 
```
dotnet restore
npm install
dotnet run
```
and everything works.

**Comment by ferrywlto** [comment]
Argh... one trick you may try is to set the ASPNETCORE_ENVIRONMENT variable to 'Development' I just see that your environment is set to Production from your screenshot.

**Comment by Jacknq** [comment]
Where do you set it? 
i think it might be connected to webpack that is installed locally only, dont want it global because of other projects.

**Comment by ferrywlto** [comment]
if you are using window, you can set it via powershell:
` setx ASPNETCORE_ENVIRONMENT DEVELOPMENT`

**Comment by Jacknq** [comment]
![image](https://user-images.githubusercontent.com/16955647/38089847-17ce10fe-3361-11e8-8303-a771664a3d3c.png)
seems to staying in production mode./

**Comment by ferrywlto** [comment]
![2018-03-30_li 2](https://user-images.githubusercontent.com/8111089/38102856-1f762994-33b7-11e8-9282-599539f35d68.jpg)

you can make sure the variable is set from System Properties -> Environment Variables...

**Comment by Jacknq** [comment]
thanks but do you really think it ll fix the missing file?

**Comment by ferrywlto** [comment]
I think so, because what `aspnet-webpack` package does is to call webpack when it is in development environment.

**Comment by Jacknq** [comment]
so only in VS2017 it seems to start, not possible in vs code
![image](https://user-images.githubusercontent.com/16955647/38424421-4a9e6f78-39b1-11e8-905e-14a4637e0d45.png)
![image](https://user-images.githubusercontent.com/16955647/38424478-7bf3863a-39b1-11e8-98ab-87c43f687cf3.png)
If I click on message it takes long time to load but nothing appears
![image](https://user-images.githubusercontent.com/16955647/38424502-8b9482ba-39b1-11e8-9a6a-be4321eaa4d4.png)

**Comment by ferrywlto** [comment]
because you are running the project in visual studio it set the launching port to random available port number (i.e. 43497). In `./vuex/action.js` the action assume you are launching the project at default port 5000, so either you set the launching port to 5000 in visual studio or edit `http://localhost:5000/initialMessages`  to `http://localhost:43497/initialMessages` and
`http://localhost:5000/fetchMessages` to `'http://localhost:43497/fetchMessages'` respectively in action.js.

**Comment by Jacknq** [comment]
Correct, finally working in VS 2017.
How to make it work in vs code?

**Comment by Jacknq** [comment]
ok, found out just 
```shell
dotnet restore && npm i
```
